coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 2%
    patch:
      default:
        target: 50%
        threshold: 5%

comment:
  layout: 'condensed_header, condensed_files, condensed_footer'
  require_changes: true

flag_management:
  default_rules:
    carryforward: true
  individual_flags:
    - name: unit
      paths:
        - src/
    - name: kat
      paths:
        - src/
    - name: integration
      paths:
        - src/

component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
        informational: true
  individual_components:
    - component_id: core
      name: edgeport/core
      paths: ['src/core/**']
    - component_id: ssh
      name: edgeport/ssh
      paths: ['src/ssh/**']
    - component_id: sftp
      name: edgeport/sftp
      paths: ['src/sftp/**']
    - component_id: smtp
      name: edgeport/smtp
      paths: ['src/smtp/**']
    - component_id: imap
      name: edgeport/imap
      paths: ['src/imap/**']
    - component_id: pop3
      name: edgeport/pop3
      paths: ['src/pop3/**']
    - component_id: ws
      name: edgeport/ws
      paths: ['src/ws/**']
    - component_id: nats
      name: edgeport/nats
      paths: ['src/nats/**']
    - component_id: mqtt
      name: edgeport/mqtt
      paths: ['src/mqtt/**']
    - component_id: stomp
      name: edgeport/stomp
      paths: ['src/stomp/**']
    - component_id: ftp
      name: edgeport/ftp
      paths: ['src/ftp/**']
    - component_id: ldap
      name: edgeport/ldap
      paths: ['src/ldap/**']
    - component_id: ldaps
      name: edgeport/ldaps
      paths: ['src/ldaps/**']
    - component_id: syslog
      name: edgeport/syslog
      paths: ['src/syslog/**']
    - component_id: smpp
      name: edgeport/smpp
      paths: ['src/smpp/**']
    - component_id: sip
      name: edgeport/sip
      paths: ['src/sip/**']
    - component_id: dns
      name: edgeport/dns
      paths: ['src/dns/**']
    - component_id: xmpp
      name: edgeport/xmpp
      paths: ['src/xmpp/**']
    - component_id: irc
      name: edgeport/irc
      paths: ['src/irc/**']
    - component_id: util
      name: edgeport/util
      paths: ['src/util/**']
    - component_id: wire
      name: edgeport/wire
      paths: ['src/wire.ts']
    - component_id: crypto
      name: edgeport/crypto
      paths: ['src/crypto/**']
    - component_id: kex
      name: edgeport/kex
      paths: ['src/kex/**']
    - component_id: auth
      name: edgeport/auth
      paths: ['src/auth/**']

ignore:
  - 'test/**/*'
  - 'coverage/**/*'
  - '**/*.spec.ts'
  - '**/*.test.ts'
  - 'wrangler.jsonc'
  - 'dist/**/*'
  - 'build.ts'
