services:
  irc:
    image: ghcr.io/ergochat/ergo@sha256:6a0eff2135cd4ca0cb2f6c464bb905e3ce61a7fc73b7095f379b0b55fb9de201
    volumes:
      - ./ircd.yaml:/ircd/ircd.yaml:ro
    healthcheck:
      test: ['CMD', 'sh', '-c', 'nc -z 127.0.0.1 6667']
      interval: 2s
      timeout: 2s
      retries: 40
    ports:
      - '127.0.0.1:6667:6667'
