services:
  irc:
    image: ghcr.io/ergochat/ergo@sha256:ef885e44f7fa19101bbbc41baef11dc280dc8107465dccaf6f0860f41b48a682
    volumes:
      - ./ircd.yaml:/ircd/ircd.yaml:ro
    healthcheck:
      test: ['CMD', 'sh', '-c', 'nc -z 127.0.0.1 6667']
      interval: 2s
      timeout: 2s
      retries: 40
    ports:
      - '127.0.0.1:6667:6667'
