services:
  dns:
    image: coredns/coredns@sha256:7efd3c635b03efd68c4e8398fc45f0d993d0e9ab016f72c1cefb0fd6d01aa286
    command: ['-conf', '/Corefile']
    volumes:
      - ./Corefile:/Corefile:ro
      - ./db.edgeport.test:/zones/db.edgeport.test:ro
      - ./db.10.0.1:/zones/db.10.0.1:ro
    ports:
      - '127.0.0.1:5354:53/tcp'
      - '127.0.0.1:5354:53/udp'
