services:
  dns:
    image: coredns/coredns@sha256:900f9c109f7a33545d3c811516e8376df9019147b750f5ce3e254468769176ea
    command: ['-conf', '/Corefile']
    volumes:
      - ./Corefile:/Corefile:ro
      - ./db.edgeport.test:/zones/db.edgeport.test:ro
      - ./db.10.0.1:/zones/db.10.0.1:ro
    ports:
      - '127.0.0.1:5354:53/tcp'
      - '127.0.0.1:5354:53/udp'
